title: Specification by Example | Concordion
author: 
description: 
baseurl: /concordion-website-2.0
exclude:  [ Gemfile, Gemfile.lock]
collections:

green: '#1baf59'
green-light: '#63ba86'
green-dark: '#00934f'
red: '#ae122a'
red-light: '#be1e2d'
red-dark: '#88172b'
off-white: '#f1f1f2'
grey-light: '#e6e7e8'
grey-dark: '#d0d2d3'

nav-height: '64px'
nav-height-mobile: '56px'

markdown: kramdown

kramdown:
  input: GFM

gems:
  - jekyll-redirect-from

whitelist:
  - jekyll-redirect-from

defaults:
  -
    scope:
      path: ""
    values:
      layout: sidenav
      description: ""
  -
    scope:
      path: "coding"
    values:
      title: "Concordion | Coding"
      heading: "Coding" 
      subheading: "Implementing the examples"
      subject: 'coding'
  -
    scope:
      path: "instrumenting"
    values:
       title: "Concordion | Instrumenting"
       heading: "Instrumenting"
       subheading: "Making the examples executable"
       subject: 'instrumenting'
  -
    scope:
      path: "tutorial"
    values:
      title: "Concordion | Getting Started"
      heading: "Getting Started"
      subheading: "The basics of creating living documents using Concordion"
      subject: 'tutorial'




