title: Specification by Example | Concordion
author: 
description: 
# TODO for sitemap 
url: http://concordion.org
baseurl: /concordion-website-2.0
exclude:  [ Gemfile, Gemfile.lock, vendor, script, .travis.yml ]
collections:

green: '#1baf59'
green-light: '#63ba86'
green-dark: '#00934f'
red: '#ae122a'
red-light: '#be1e2d'
red-dark: '#88172b'
off-white: '#f1f1f2'
grey-light: '#e6e7e8'
grey-dark: '#d0d2d3'
text: '#5f5f60'
text-light: '#7f7f82'

nav-height: '64px'
nav-height-mobile: '56px'

markdown: kramdown

kramdown:
  input: GFM

gems:
  - jekyll-redirect-from

whitelist:
  - jekyll-redirect-from

google_analytics: UA-58172036-1

defaults:
  -
    scope:
      path: ""
    values:
      layout: sidenav
      description: ""
  -
    scope:
      path: "redirect.html"
    values:
      layout: 
  -
    scope:
      path: "coding"
    values:
      heading: "Coding" 
      subheading: "Implementing the examples"
      subject: "coding"
      include: 'coding.md'
      next_page: 'technique'
      next_page_text: 'Hints and Tips'
  -
    scope:
      path: "discussing"
    values:
      title: "Concordion | Discussing"
      heading: "Discussing"
      subheading: "Collaboratively specifying examples"
      subject: "discussing"
      description: "Collaborative Specification techniques for discussing Concordion specifications. Exploring stories, acceptance criteria and examples using specification workshops, three amigos sessions or example mapping techniques. Discussing examples is the most important aspect of Specification by Example (SBE) and Behaviour Driven Development (BDD)."
      include: 'discussing.md'
      next_page: 'documenting'
      next_page_text: 'Documenting'
  -
    scope:
      path: "documenting"
    values:
      heading: "Documenting"
      subheading: "Creating specifications with Markdown or HTML"
      subject: "documenting"
      include: 'documenting.md'
      next_page: 'instrumenting'
      next_page_text: 'Instrumenting'
  -
    scope:
      path: "download"
    values:
      heading: "Download"
      subheading: "Downloads and release notes"
      subject: "download"
      include: 'download.md'
  -
    scope:
      path: "extensions"
    values:
      heading: "Extensions"
      subheading: "Enhancing Concordion with flexible features"
      subject: "extensions"
      include: 'extensions.md'
      next_page: 'integrations'
      next_page_text: 'Integrations'
  -
    scope:
      path: "instrumenting"
    values:
      heading: "Instrumenting"
      subheading: "Making the examples executable"
      subject: 'instrumenting'
      include: 'instrumenting.md'
      next_page: 'coding'
      next_page_text: 'Coding'
  -
    scope:
      path: "integrations"
    values:
      heading: "Integrations"
      subheading: "Integrating Concordion with other tools"
      subject: 'integrations'
      include: 'integrations.md'
      next_page: 'questions'
      next_page_text: 'FAQ'
  -
    scope:
      path: "questions"
    values:
      heading: "FAQ"
      subheading: "Frequently Asked Questions about Concordion"
      subject: 'questions'
      include: 'questions.md'
      next_page: 'download'
      next_page_text: 'Download'
  -
    scope:
      path: "technique"
    values:
      heading: "Hints and Tips"
      subheading: "Good practices for using Concordion"
      subject: 'technique'
      next_page: 'discussing'
      next_page_text: 'discussing'
      include: 'technique.md'
      next_page: 'extensions'
      next_page_text: 'Extensions'
  -
    scope:
      path: "tutorial"
    values:
      heading: "Getting Started"
      subheading: "The basics of creating living documents using Concordion"
      subject: 'tutorial'
      include: 'tutorial.md'
      next_page: 'discussing'
      next_page_text: 'Discussing'
      sitemap:
        priority: 0.7
